"""
Python bindings for libtofcam API
"""
from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['TOFCam', 'TOFControl', 'TOFFrame', 'TOFHatModel', 'TOFMetadata']
class TOFCam:
    def __init__(self, arg0: TOFHatModel) -> None:
        ...
    def captureFrame(self) -> TOFFrame:
        ...
    def close(self) -> int:
        ...
    def getControl(self, control: TOFControl) -> int:
        ...
    def open(self) -> int:
        ...
    def setControl(self, control: TOFControl, value: typing.SupportsInt) -> int:
        ...
    def startStream(self) -> None:
        ...
    def stopStream(self) -> None:
        ...
class TOFControl:
    """
    Members:
    
      EXPOSURE
    
      MODULATION_FREQUENCY
    """
    EXPOSURE: typing.ClassVar[TOFControl]  # value = <TOFControl.EXPOSURE: 0>
    MODULATION_FREQUENCY: typing.ClassVar[TOFControl]  # value = <TOFControl.MODULATION_FREQUENCY: 1>
    __members__: typing.ClassVar[dict[str, TOFControl]]  # value = {'EXPOSURE': <TOFControl.EXPOSURE: 0>, 'MODULATION_FREQUENCY': <TOFControl.MODULATION_FREQUENCY: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class TOFFrame:
    def getAmplitude(self) -> numpy.typing.NDArray[numpy.uint16]:
        ...
    def getDCS(self, arg0: typing.SupportsInt) -> numpy.typing.NDArray[numpy.uint16]:
        ...
    def getDistance(self) -> numpy.typing.NDArray[numpy.uint16]:
        ...
    def getMetadata(self) -> TOFMetadata:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def width(self) -> int:
        ...
class TOFHatModel:
    """
    Members:
    
      TOF_HAT_670
    """
    TOF_HAT_670: typing.ClassVar[TOFHatModel]  # value = <TOFHatModel.TOF_HAT_670: 0>
    __members__: typing.ClassVar[dict[str, TOFHatModel]]  # value = {'TOF_HAT_670': <TOFHatModel.TOF_HAT_670: 0>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class TOFMetadata:
    @property
    def frameNumber(self) -> int:
        ...
    @property
    def timestamp(self) -> int:
        ...
